ignore:
  - "src/**/*.{js,ts,jsx,tsx}",
  - "test/**/*.spec.{js,jsx,ts,tsx}",
  - "test/**/*.it.{js,jsx,ts,tsx}",
  - "test/**/*.test.{js,jsx,ts,tsx}",
  - "test/**/*.e2e.{js,jsx,ts,tsx}",
  - "!node_modules/**",
  - "!src/swagger.ts",
  - "!src/utils/**/*.{js,ts,jsx,tsx}"
